# Generated by Django 3.1.7 on 2021-03-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='cedula',
            field=models.SlugField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contribucion',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contribuciones', to='hamster.beneficiario'),
        ),
    ]
