# Generated by Django 3.1.7 on 2021-07-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={'ordering': ['municipio', 'nombre'], 'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nombre']},
        ),
    ]
