# Generated by Django 3.1.7 on 2021-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0002_auto_20210712_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='territorio',
        ),
        migrations.AddField(
            model_name='municipio',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='Extensión en Km^2', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='region',
            field=models.CharField(choices=[('raccs', 'Región Autónoma de la Costa Caribe Sur'), ('raccn', 'Región Autónoma de la Costa Caribe Norte')], default='raccs', max_length=5),
        ),
    ]
