# Generated by Django 3.2.8 on 2021-11-04 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0002_transmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmision',
            name='codigo',
            field=models.TextField(blank=True, help_text='Código Embed/Insertar </> de la transmisión.', null=True, validators=[django.core.validators.RegexValidator(message='El campo debe contener el código <embed>.', regex='<iframe')], verbose_name='Código </>'),
        ),
    ]
