# Generated by Django 3.1.7 on 2021-10-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0003_auto_20210716_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['tipo', 'estado', '-fecha', 'autor'], 'permissions': [('crear_noticia', 'Redacta Noticias'), ('crear_informe', 'Redacta Informes'), ('publicar_noticia', 'Publica Noticias'), ('publicar_informe', 'Publica Informes')], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='actividades_ec',
            field=models.ManyToManyField(help_text='Actividades económicas desarrolladas en la comunidad.', limit_choices_to=models.Q(tabla__tabla='actividades_ec'), related_name='_comunidad_actividades_ec_+', to='suir.DetalleTabla'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.ForeignKey(limit_choices_to=models.Q(tabla__tabla='cargos'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='sector',
            field=models.ForeignKey(help_text='Sector social que atiende la entidad.', limit_choices_to=models.Q(tabla__tabla='sectores'), on_delete=django.db.models.deletion.RESTRICT, to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='desagregaciones',
            field=models.ManyToManyField(help_text='Desagregaciones del indicador', limit_choices_to=models.Q(tabla__tabla='desagregaciones'), related_name='_indicador_desagregaciones_+', to='suir.DetalleTabla'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='estado',
            field=models.ForeignKey(help_text='Posibles valores: borrador, pendiente, publicado', limit_choices_to=models.Q(tabla__tabla='estados_pub'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_estados', related_query_name='indicador_estado', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='ficha',
            field=models.FileField(blank=True, help_text='Documento en Formato PDF', null=True, upload_to='suir/docs/indicadores/', verbose_name='Ficha Técnica'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='periodicidad',
            field=models.ForeignKey(limit_choices_to=models.Q(tabla__tabla='periodos'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_periodos', related_query_name='indicador_periodo', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='sector',
            field=models.ForeignKey(help_text='Sector social al que pertenece el indicador.', limit_choices_to=models.Q(tabla__tabla='sectores'), on_delete=django.db.models.deletion.RESTRICT, related_name='indicadores_sectores', related_query_name='indicador_sector', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tipo_valor',
            field=models.ForeignKey(help_text='Tipo de valor del indicador.', limit_choices_to=models.Q(tabla__tabla='tipos_valor'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_tipos_valores', related_query_name='indicador_tipo_valor', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='sector',
            field=models.ForeignKey(help_text='Sector social que atiende la institución', limit_choices_to=models.Q(tabla__tabla='sectores'), on_delete=django.db.models.deletion.RESTRICT, related_name='instituciones_sectores', related_query_name='institucion_sector', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.ForeignKey(help_text='Posibles valores: borrador, pendiente, publicado', limit_choices_to=models.Q(tabla__tabla='estados_pub'), on_delete=django.db.models.deletion.RESTRICT, related_name='publicaciones_estados', related_query_name='publicacion_estado', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='publicado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tags',
            field=models.TextField(blank=True, help_text='Etiquetas separadas por coma.', null=True, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo',
            field=models.ForeignKey(limit_choices_to=models.Q(tabla__tabla='tipos_pub'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_tipos', related_query_name='publicacion_tipo', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='comunidad',
            field=models.ForeignKey(default=1, help_text='Comunidad donde se levantó el dato.', on_delete=django.db.models.deletion.RESTRICT, to='suir.comunidad'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='estado',
            field=models.ForeignKey(help_text='Posibles valores: borrador, pendiente, publicado', limit_choices_to=models.Q(tabla__tabla='estados_pub'), on_delete=django.db.models.deletion.RESTRICT, related_name='valores_estados', related_query_name='valor_estado', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='etnia',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(tabla__tabla='etnias'), null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='valores_etnias', related_query_name='valor_etnia', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='ficha',
            field=models.FileField(blank=True, help_text='Ficha en formato PDF', null=True, upload_to='suir/docs/fichas/'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='rango_edad',
            field=models.ForeignKey(help_text='Rango de edad (si aplica).', limit_choices_to=models.Q(tabla__tabla='rangos_edad'), null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='valores_rangos_edad', related_query_name='valor_rango_edad', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Si aplica al tipo de valor del indicador.', max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='valorindicador',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor'),
        ),
    ]
