# Generated by Django 3.2.8 on 2021-11-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0003_alter_transmision_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transmision',
        ),
    ]
