# Generated by Django 3.2.8 on 2021-11-09 15:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suir', '0004_delete_transmision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(help_text='Campo empleado para la interfaz administrativa.', max_length=200, verbose_name='Descripción')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inicio')),
                ('final', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Culminación')),
                ('codigo', models.TextField(blank=True, help_text='Código Embed/Insertar </> de la transmisión.', null=True, validators=[django.core.validators.RegexValidator(message='El campo debe contener el código <embed>.', regex='<iframe')], verbose_name='Código </>')),
                ('origen', models.CharField(choices=[('yt', 'YouTube'), ('fb', 'Facebook')], default='yt', max_length=2)),
                ('especial', models.BooleanField(default=False, help_text='Seleccionar en caso que la transmisión no corresponda al noticiero RBS.', verbose_name='Transmisión Especial')),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmisión',
                'verbose_name_plural': 'Transmisiones',
                'ordering': ['inicio'],
                'get_latest_by': 'inicio',
            },
        ),
    ]
