# Generated by Django 3.1.7 on 2021-10-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0004_auto_20211001_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='media/suir/docs/publicaciones/'),
        ),
    ]
