# Generated by Django 3.1.7 on 2021-10-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0005_auto_20211004_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.ForeignKey(help_text='Posibles valores: borrador, pendiente, publicado', on_delete=django.db.models.deletion.RESTRICT, related_name='publicaciones_estados', related_query_name='publicacion_estado', to='suir.detalletabla'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_tipos', related_query_name='publicacion_tipo', to='suir.detalletabla'),
        ),
    ]
