# Generated by Django 3.1.7 on 2021-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0007_auto_20211005_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
